/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MobilePreviewRouteImport } from './routes/mobile-preview'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DialpadRouteImport } from './routes/dialpad'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AiSearchRouteImport } from './routes/ai-search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVoiceAgentRouteImport } from './routes/app.voice-agent'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReviewsRouteImport } from './routes/app.reviews'
import { Route as AppQuotesRouteImport } from './routes/app.quotes'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppCallsRouteImport } from './routes/app.calls'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiSearchRouteImport } from './routes/app.ai-search'
import { Route as AppAiEmployeeRouteImport } from './routes/app.ai-employee'
import { Route as AppAiBrainRouteImport } from './routes/app.ai-brain'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePreviewRoute = MobilePreviewRouteImport.update({
  id: '/mobile-preview',
  path: '/mobile-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DialpadRoute = DialpadRouteImport.update({
  id: '/dialpad',
  path: '/dialpad',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchRoute = AiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceAgentRoute = AppVoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSearchRoute = AppAiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => AppRoute,
} as any)
const AppAiEmployeeRoute = AppAiEmployeeRouteImport.update({
  id: '/ai-employee',
  path: '/ai-employee',
  getParentRoute: () => AppRoute,
} as any)
const AppAiBrainRoute = AppAiBrainRouteImport.update({
  id: '/ai-brain',
  path: '/ai-brain',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-search': typeof AiSearchRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dialpad': typeof DialpadRoute
  '/inbox': typeof InboxRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/ai-brain': typeof AppAiBrainRoute
  '/app/ai-employee': typeof AppAiEmployeeRoute
  '/app/ai-search': typeof AppAiSearchRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/calls': typeof AppCallsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice-agent': typeof AppVoiceAgentRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-search': typeof AiSearchRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dialpad': typeof DialpadRoute
  '/inbox': typeof InboxRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/ai-brain': typeof AppAiBrainRoute
  '/app/ai-employee': typeof AppAiEmployeeRoute
  '/app/ai-search': typeof AppAiSearchRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/calls': typeof AppCallsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice-agent': typeof AppVoiceAgentRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-search': typeof AiSearchRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dialpad': typeof DialpadRoute
  '/inbox': typeof InboxRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/ai-brain': typeof AppAiBrainRoute
  '/app/ai-employee': typeof AppAiEmployeeRoute
  '/app/ai-search': typeof AppAiSearchRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/calls': typeof AppCallsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice-agent': typeof AppVoiceAgentRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-search'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/dialpad'
    | '/inbox'
    | '/mobile-preview'
    | '/onboarding'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/app/ai-brain'
    | '/app/ai-employee'
    | '/app/ai-search'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/calls'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/jobs'
    | '/app/payments'
    | '/app/quotes'
    | '/app/reviews'
    | '/app/settings'
    | '/app/voice-agent'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-search'
    | '/auth'
    | '/dashboard'
    | '/dialpad'
    | '/inbox'
    | '/mobile-preview'
    | '/onboarding'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/app/ai-brain'
    | '/app/ai-employee'
    | '/app/ai-search'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/calls'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/jobs'
    | '/app/payments'
    | '/app/quotes'
    | '/app/reviews'
    | '/app/settings'
    | '/app/voice-agent'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/ai-search'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/dialpad'
    | '/inbox'
    | '/mobile-preview'
    | '/onboarding'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/app/ai-brain'
    | '/app/ai-employee'
    | '/app/ai-search'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/calls'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/jobs'
    | '/app/payments'
    | '/app/quotes'
    | '/app/reviews'
    | '/app/settings'
    | '/app/voice-agent'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSearchRoute: typeof AiSearchRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DialpadRoute: typeof DialpadRoute
  InboxRoute: typeof InboxRoute
  MobilePreviewRoute: typeof MobilePreviewRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-preview': {
      id: '/mobile-preview'
      path: '/mobile-preview'
      fullPath: '/mobile-preview'
      preLoaderRoute: typeof MobilePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialpad': {
      id: '/dialpad'
      path: '/dialpad'
      fullPath: '/dialpad'
      preLoaderRoute: typeof DialpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search': {
      id: '/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof AiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice-agent': {
      id: '/app/voice-agent'
      path: '/voice-agent'
      fullPath: '/app/voice-agent'
      preLoaderRoute: typeof AppVoiceAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotes': {
      id: '/app/quotes'
      path: '/quotes'
      fullPath: '/app/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls': {
      id: '/app/calls'
      path: '/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-search': {
      id: '/app/ai-search'
      path: '/ai-search'
      fullPath: '/app/ai-search'
      preLoaderRoute: typeof AppAiSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-employee': {
      id: '/app/ai-employee'
      path: '/ai-employee'
      fullPath: '/app/ai-employee'
      preLoaderRoute: typeof AppAiEmployeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-brain': {
      id: '/app/ai-brain'
      path: '/ai-brain'
      fullPath: '/app/ai-brain'
      preLoaderRoute: typeof AppAiBrainRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiBrainRoute: typeof AppAiBrainRoute
  AppAiEmployeeRoute: typeof AppAiEmployeeRoute
  AppAiSearchRoute: typeof AppAiSearchRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCallsRoute: typeof AppCallsRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppJobsRoute: typeof AppJobsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVoiceAgentRoute: typeof AppVoiceAgentRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiBrainRoute: AppAiBrainRoute,
  AppAiEmployeeRoute: AppAiEmployeeRoute,
  AppAiSearchRoute: AppAiSearchRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCallsRoute: AppCallsRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppJobsRoute: AppJobsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVoiceAgentRoute: AppVoiceAgentRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSearchRoute: AiSearchRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DialpadRoute: DialpadRoute,
  InboxRoute: InboxRoute,
  MobilePreviewRoute: MobilePreviewRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
